/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:bf970351-c37b-4770-9b8c-42f2a60ddc34",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_2LTMMFRnu",
    "aws_user_pools_web_client_id": "2tl5jtn7lbp8n9n95s1lmtp7bm",
    "oauth": {}
};


export default awsmobile;
